name: Write Secret to File

on: [push]

jobs:
  write_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write secret to file
        run: |
          echo "${{ secrets.NIILO_PUBLIC_SECRET }}" > secret.txt
        shell: bash

      - name: Verify file (hidden in logs)
        run: ls -l secret.txt  # Will NOT print content

      - name: Read file
        run: cat secret.txt  # For testing, but this exposes the secret in logs!!!
